### ISSUE TITLE
Can not run the extension for Windows

### ISSUE THREAD

**Issue by seachicken** [cli/gh-extension-precompile#1]
Thanks for creating Action, and I look forward to making binary extensions much easier to create.

I tried to run this Action [here](https://github.com/seachicken/gh-poi/commit/9711ca75cf6e1b97ffeb77c5b865f581671f4bc0). But, does not work on Windows.

**My Environment**
- OS: Windows 10
- gh --version: v2.2.0

**To Reproduce**
1. `gh extension install seachicken/gh-poi`
2. `gh poi`
3. View the output:
   ```
   failed to run extension: exec: "C:\\Users\\name\\AppData\\Local\\GitHub CLI\\extensions\\gh-poi\\gh-poi": file does not exist
   ```

I tried adding the `.exe` extension to the binary name "C:\\Users\\name\\AppData\\Local\\GitHub CLI\\extensions\\gh-poi\\gh-poi.exe", and it worked fine.

**Comment by vilmibm** [comment]
thanks for the report. I'll do some testing on windows; either we need to dispatch differently or just give up and use a .exe extension. I am very surprised that windows requires an extension like that.

**Comment by vilmibm** [comment]
This PR will fix binary extension support on windows: https://github.com/cli/cli/pull/4717

**Comment by seachicken** [comment]
Thank you for the work!

**Comment by vilmibm** [comment]
Thanks for the report! Sorry I didn't recognize the issue sooner.

**Comment by vilmibm** [comment]
cli/li#4717 is merged; i'll close this issue after the next `gh` release.

**Comment by seachicken** [comment]
Ok, thanks a lot 😄

**Comment by vilmibm** [comment]
Closing this as v2.3.0 is releasing now
