### ISSUE TITLE
Ima! 

### ISSUE THREAD

**Issue by Imansame** [cli/gh-extension-precompile#17]
`![Screenshot_۲۰۲۲-۰۴-۱۳-۲۰-۴۴-۴۴-۶۵۷_com.smartphoneremote.androidscriptfree.jpg](https://user-images.githubusercontent.com/103526878/163224872-8cc32d4e-23d8-43e8-b41a-47dc11dacfe9.jpg)`

**Comment by stemar94** [comment]
@mislav 
Aren't you guys from GitHub?
Isn't there a way to wipe/hide such issues?
IMO closing is not enough.

**Comment by mislav** [comment]
@stemar94 GitHub's spam filters catch a lot of content, but not all. Sorry about the noise

**Comment by stemar94** [comment]
@mislav No need to be sorry. I was just wondering, if there isn't a possibility especially for you (@GitHub) to properly get rid of the "noise".

**Comment by mislav** [comment]
I can delete this issue, but I'd rather keep it to train future spam-prevention efforts.

Deleting the issue wouldn't help the noise, I'm afraid, since the noise was already made.
