### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by mislav** [cli/gh-extension-precompile#2]
First of all, thanks for this great action!

The following is my list of notes as I'm reading over the functionality in this repo:

* `inputs.platforms` - I'm thinking that this shouldn't be configurable, and should instead match the list of platforms that we officially support with gh. If there is popularly requested platform, we would simply add it to the action instead of encouraging people to configure it themselves. That way the added platform will propagate to all gh extensions that use this Action.

* Triggers for the action: currently, precompiling the binaries on push to `refs/tags/v*` is fine, but I wonder whether we can enable this Action to precompile your extension for you even if you don't explicitly use git tags. For example, the Action could precompile the extension on every push to the `main` branch, or it could be triggered by a `workflow_dispatch` event to allow releasing one's extension directly from the CLI. In these cases, the Action could simply increment the last version number in the repo and use it for making the Release.

* Prereleases - I really like that this is available 👍 

* `build_script_override` - this is great for non-Go actions 👌 

* `actions/setup-go@v2` - should we explicitly define which Go version should we use for compiling extensions? We could use the same version we use for gh.

* Action versioning - Should we suggest that people configure their workflows like `uses: cli/gh-extension-precompile@v1` and we change the main branch of this repo to be called `v1`? That leaves us an option in the future to make breaking changes to this Action by switching the mainline to `v2` or whatever.

**Comment by vilmibm** [comment]
> `inputs.platforms` - I'm thinking that this shouldn't be configurable, and should instead match the list of platforms that we officially support with gh. If there is popularly requested platform, we would simply add it to the action instead of encouraging people to configure it themselves. That way the added platform will propagate to all gh extensions that use this Action.

Makes sense to me; I'm fine with adding support for this if it ends up being requested.

> Triggers for the action: currently, precompiling the binaries on push to `refs/tags/v*` is fine, but I wonder whether we can enable this Action to precompile your extension for you even if you don't explicitly use git tags. For example, the Action could precompile the extension on every push to the `main` branch, or it could be triggered by a `workflow_dispatch` event to allow releasing one's extension directly from the CLI. In these cases, the Action could simply increment the last version number in the repo and use it for making the Release.

What is your concern, here? That the tagging is overcomplicated for users? I like the explicitness of it and didn't feel like it was too conceptually difficult but I'd like to hear more of your thoughts.

> `actions/setup-go@v2` - should we explicitly define which Go version should we use for compiling extensions? We could use the same version we use for gh.

I discussed this with Sam and concluded there wasn't a tremendous need to set a Go version (or have it be configurable by the extension author). I don't see any issues with letting `setup-go` decide on what Go version to bring in, nor do I see any advantage to matching `gh`'s version of Go. Extensions should be flexible in what Go compiler features they want to use. I'd prefer to keep this how it is for now and see if it's something we get requests to change.

> Action versioning - Should we suggest that people configure their workflows like `uses: cli/gh-extension-precompile@v1` and we change the main branch of this repo to be called `v1`? That leaves us an option in the future to make breaking changes to this Action by switching the mainline to `v2` or whatever.

yep, and I was going to set all that up once this had been sufficiently reviewed.

**Comment by vilmibm** [comment]
re: Go versioning, after further discussion with @samcoe we agreed to pin ^_^() I'm going to go with 1.16.

**Comment by mislav** [comment]
> What is your concern, here? That the tagging is overcomplicated for users? I like the explicitness of it and didn't feel like it was too conceptually difficult but I'd like to hear more of your thoughts.

I don't think tagging is a big barrier to entry, but compared to scripting extensions where I can just push to main to "publish" a new version, triggering a build of a binary extension forces me to create a git tag. This requirement is fine if it stays like this, but I was wondering whether the Action would be flexible enough to configure on `push` or `workflow_dispatch` as well. Right now I don't think it is because the build script requires that there is a git tag.

For example, one place where it's not possible to create a git tag right now (to my knowledge) is the web interface. So I could merge a PR to my extension from the web, but to publish and update I would need to open a terminal to manually create a git tag.

**Comment by vilmibm** [comment]
I'd like to leave it explicit for tag pushes right now, but agree that the workflow should function without a tag. I'll tackle that in the future, though, as it can be an additive change.
