### ISSUE TITLE
The action does not allow you to publish a release first

### ISSUE THREAD

**Issue by heaths** [cli/gh-extension-precompile#7]
From [my build failure](https://github.com/heaths/gh-label/runs/4401987345?check_suite_focus=true#step:5:72), it's apparent that the action does not allow you to publish a release, which I typically do in projects to create release notes as I'm publishing. Rather than forcing extension authors to use a certain strategy to publish binaries, could build_and_release.sh be updated to skip creating a release if one already exists and just upload artifacts e.g., https://github.com/heaths/gh-label/blob/61421314d2f64c23f51173a744dfd2f4fc774bda/.github/workflows/release.yml#L36-L39

Raw git commit logs aren't always the neatest changelog, and some others may want to handcraft release notes in order to publish.

**Comment by vilmibm** [comment]
I like the idea of uploading if the release already exists!

I am about to be OOO through to the new year so I won't be able to work on it myself but a PR would certainly be welcome.

**Comment by heaths** [comment]
Before I you go (I'm also about to go on holiday through the new year, though woodworking and showshoeing will fill most of my time I do plan to do a bit of focused time on side projects), would you prefer any error output be hidden or just treat it like verbose logging?

I was considering two approaches: try creating a release and if that fails try updating it, or check if it exists (only a single log line in that case) then create or update accordingly. The latter is 1 extra call unconditionally, though perf really isn't a factor in this scenario either way.

Enjoy your holiday!

**Comment by mislav** [comment]
> try creating a release and if that fails try updating it

I like this approach because it's less prone to race conditions. (Doing a check beforehand runs a risk of state having changed shortly after the check was performed.)
